### ISSUE TITLE
Project still Active?

### ISSUE THREAD

**Issue by Daniel-dev22** [kpishere/Net485#7]
Is this project still active? 

I'm moving to a house with a Rheem Econet thermostat + electric hot water heater.

I'm interested in getting logs if it helps move this project forward and potentially provide a path to locally controlling these 2 devices.

**Comment by MoralCode** [comment]
also interested in whether this is active! would love to try and get some kind of group/community together to work on getting this documented and out there for people to use if there's people still actively around!

**Comment by Daniel-dev22** [comment]
> also interested in whether this is active! would love to try and get some kind of group/community together to work on getting this documented and out there for people to use if there's people still actively around!

This might be helpful. We were able to decode econet which uses rs485
https://github.com/Daniel-dev22/esphome-econet/tree/dev
